### ISSUE TITLE
Incompatable with Ansible 2.9+

### ISSUE THREAD

**Issue by tst-nstires** [MindPointGroup/RHEL6-STIG#163]
The filter 'version_compare' has been deprecated for some time. I see a ticket was opened on this, but the issue was closed without being addressed.

[Previous ticket (154)](https://github.com/MindPointGroup/RHEL6-STIG/issues/154)

Error message:
```
TASK [mindpointgroup.stig_rhel6 : Check OS version and family] *****************
task path: /home/nick/.ansible/roles/mindpointgroup.stig_rhel6/tasks/main.yml:1
fatal: [ec1-1-1-1.compute-1.amazonaws.com]: FAILED! => {
    "msg": "The conditional check 'ansible_os_family == 'RedHat' and ansible_distribution_major_version | version_compare('6', '==')' failed. The error was: template error while templating string: no filter named 'version_compare'. String: {% if ansible_os_family == 'RedHat' and ansible_distribution_major_version | version_compare('6', '==') %} True {% else %} False {% endif %}"
}
```

That playbook has two tasks in main that call that filter:
```
- name: Check OS version and family
  assert:
      that: ansible_os_family == 'RedHat' and ansible_distribution_major_version | version_compare('6', '==')
      msg: "This role can only be run against RHEL/CENTOS 6. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  tags:
      - always

- name: Check ansible version
  assert:
      that: ansible_version.full | version_compare(rhel6stig_min_ansible_version, '>=')
      msg: You must use Ansible {{ rhel6stig_min_ansible_version }} or greater
  tags:
      - always
```
