### ISSUE TITLE
V-38604 ypbind service in cat2.yml not properly written, breaks in ansible v2

### ISSUE THREAD

**Issue by defionscode** [MindPointGroup/RHEL6-STIG#26]
The following:

```yml
- name: V-38604 Medium  The ypbind service must not be running
  service: name=ypbind state=stopped enabled=no
  register: ypbind_test
  when: ypbind_test.msg is defined and "'FAIL' not in ypbind_test.msg"
  tags: [ 'cat2' , 'V-38604' , 'insecure_services' , 'ypbind' ]
```

shouldn't work in ansible v1, but it does and it improperly skips the task every time. The `register` var being used in the conditional in the same task is not proper. 

TODO: Refactor so that the presence of ypbind is checked in a separate task prior to attempting to stop/disabling the service.
