### ISSUE TITLE
Tasks need to be refactored into YAML literal

### ISSUE THREAD

**Issue by defionscode** [MindPointGroup/RHEL6-STIG#29]
From this:
```yml
- name: V-38677 High  The NFS server must not have the insecure file locking option enabled
  replace: dest=/etc/exports regexp='insecure_locks'
  tags: [ 'cat1' , 'V-38677' , 'nfs' ]
```
to this:

```yml
- name: V-38677 High  The NFS server must not have the insecure file locking option enabled
  replace: 
      dest: /etc/exports 
      regexp: 'insecure_locks'
  tags: [ 'cat1' , 'V-38677' , 'nfs' ]
```
