### ISSUE TITLE
Remove rhel6stig_* prefix from all variables

### ISSUE THREAD

**Issue by shepdelacreme** [MindPointGroup/RHEL6-STIG#44]
I think we should remove the rhel6stig_ prefix from all variables. I don't see that it adds anything since they all already exist in the rhel6stig role. Also if you parameterizing the role and arew using a variable when you call it. i.e.
```
roles:
    - role: "{{ baseline }}"
      rhel6stig_fullauto: true
      rhel6stig_cat2: true
      rhel6stig_cat3: true
```
or 
```
roles:
    - { role: "{{ baseline }}", rhel6stig_fullauto: true, rhel6stig_cat2: true, rhel6stig_cat3: true, tags: ['cat1', 'rhel6']}
````
Then those prefixes can become an issue. If I wanted to be able to call rhel6stig, rhel5stig, ubuntu14cis baselines in this way with parameters then it would be a problem. Also as a bonus it makes the variable names shorter.

Will defer to the group for voting on this though.

**Comment by defionscode** [comment]
I'm not too sure I understand when the prefixes would become an issue in the role calls...

**Comment by shepdelacreme** [comment]
If I were to call the roll this way and I wanted to be able to pass in "baseline" as a parameter then the rhel6stig_ wouldn't apply if it were the rhel5stig etc. By making it generic then "fullauto" can be a variable that is consistent across baselines.

I call the roll this way in the PR I made for the role testing updates. So narrow use case right now I guess.

```
- name: "{{baseline}} | Applying Baselines"
  sudo: yes
  hosts: test_servers
  vars:
      baseline: rhel6-stig
  # Need to make the rhel6stig_* vars generic so this can be used across
  # different baseline versions/types.
  # Requires change in STIG baseline vars file.
  roles:
      - role: "{{ baseline }}"
        rhel6stig_fullauto: true
        rhel6stig_cat2: true
        rhel6stig_cat3: true
```
