### ISSUE TITLE
Ansible `stdout_lines` bug when used with the file module

### ISSUE THREAD

**Issue by mliudev** [MindPointGroup/RHEL6-STIG#97]
There's currently a bug in Ansible where `stdout_lines` always appends a new line. This new line causes the file module to choke with `"msg": "file () is absent, cannot continue"`.

I'm working around this by using the difference set filter, for example:

```
- name: "MEDIUM | V-38465 | PATCH | Library files must have mode 0755 or less permissive"
  file:
      state: file
      mode: "go-w"
      path: "{{ item }}"
  when: library_perms_audit.stdout
  with_items: "{{ library_perms_audit.stdout_lines | difference(['']) }}"
  tags:
      - cat2
      - medium
      - V-38465
      - patch
      - file_perms
```

The open Ansible issue is here: https://github.com/ansible/ansible/issues/15099. This issue happens in quite a few places in cat2.yml.
